using GatorLibrary;

Library gatorLibrary = new();
Console.WriteLine(gatorLibrary.InsertBook(101, "Introduction to Algorithms", "Thomas H. Cormen", "Yes"));
Console.WriteLine(gatorLibrary.InsertBook(48, "Data Structures and Algorithms", "Sartaj Sahni", "Yes"));
Console.WriteLine(gatorLibrary.PrintBook(48));
Console.WriteLine(gatorLibrary.InsertBook(132, "Operating System Concepts", "Abraham Silberschatz", "Yes"));
Console.WriteLine(gatorLibrary.InsertBook(25, "Computer Networks", "Andrew S. Tanenbaum", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(120, 48, 2));
Console.WriteLine(gatorLibrary.BorrowBook(132, 101, 1));
Console.WriteLine(gatorLibrary.InsertBook(73, "Introduction to the Theory of Computation", "Michael Sipser", "Yes"));
Console.WriteLine(gatorLibrary.InsertBook(12, "Artificial Intelligence: A Modern Approach", "Stuart Russell", "Yes"));
Console.WriteLine(gatorLibrary.InsertBook(6, "Database Management Systems", "Raghu Ramakrishnan", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(144, 48, 3));
Console.WriteLine(gatorLibrary.BorrowBook(140, 48, 3));
Console.WriteLine(gatorLibrary.BorrowBook(142, 48, 2));
Console.WriteLine(gatorLibrary.BorrowBook(138, 12, 4));
Console.WriteLine(gatorLibrary.BorrowBook(150, 12, 3));
Console.WriteLine(gatorLibrary.BorrowBook(162, 12, 1));
Console.WriteLine(gatorLibrary.ReturnBook(120, 48));
Console.WriteLine(gatorLibrary.FindClosestBook(9));
Console.WriteLine(gatorLibrary.DeleteBook(12));
Console.WriteLine(gatorLibrary.ColorFlipCount());
Console.WriteLine(gatorLibrary.InsertBook(125, "Computer Organization and Design", "David A. Patterson", "Yes"));
Console.WriteLine(gatorLibrary.InsertBook(180, "Introduction to Software Engineering", "Ian Sommerville", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(111, 73, 3));
Console.WriteLine(gatorLibrary.BorrowBook(52, 73, 1));
Console.WriteLine(gatorLibrary.InsertBook(115, "Operating Systems: Internals and Design Principles", "William Stallings", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(153, 25, 2));
Console.WriteLine(gatorLibrary.PrintBooks(10, 150));
Console.WriteLine(gatorLibrary.InsertBook(210, "Machine Learning: A Probabilistic Perspective", "Kevin P.Murphy", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(171, 25, 3));
Console.WriteLine(gatorLibrary.BorrowBook(2, 132, 2));
Console.WriteLine(gatorLibrary.FindClosestBook(50));
Console.WriteLine(gatorLibrary.BorrowBook(18, 101, 2));
Console.WriteLine(gatorLibrary.InsertBook(80, "Software Engineering: A Practitioner's Approach", "Roger S.Pressman", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(210, 210, 1));
Console.WriteLine(gatorLibrary.BorrowBook(43, 73, 1));
Console.WriteLine(gatorLibrary.InsertBook(60, "Introduction to Computer Graphics", "David F. Rogers", "Yes"));
Console.WriteLine(gatorLibrary.PrintBook(210));
Console.WriteLine(gatorLibrary.InsertBook(4, "Design Patterns: Elements of Reusable Object-Oriented Software", "Erich Gamma", "Yes"));
Console.WriteLine(gatorLibrary.InsertBook(2, "Introduction to the Theory of Computation", "Michael Sipser", "Yes"));
Console.WriteLine(gatorLibrary.BorrowBook(34, 210, 2));
Console.WriteLine(gatorLibrary.InsertBook(65, "Computer Networks: Principles, Protocols, and Practice", "Olivier Bonaventure", "Yes"));
Console.WriteLine(gatorLibrary.ColorFlipCount());
Console.WriteLine(gatorLibrary.DeleteBook(125));
Console.WriteLine(gatorLibrary.DeleteBook(115));
Console.WriteLine(gatorLibrary.DeleteBook(210));
Console.WriteLine(gatorLibrary.ColorFlipCount());
Console.WriteLine(gatorLibrary.DeleteBook(25));
Console.WriteLine(gatorLibrary.DeleteBook(80));
Console.WriteLine(gatorLibrary.ColorFlipCount());